spring.application.name=accountService

server.servlet.context-path=/accountService

# Server
server.port=8080

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://26.41.201.183:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=2162004

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=4
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#jwt
jwt.secret=/dDMtv80KZSwPmYUT6r0Qj6LJNpSwCmwt7hqv0x5hc+RgNz3v6bFYVF3IrWjTsxLj//ddVXi34mNrEZ454nmGg==
jwt.expiration=86400000
saving.service.url=http://saving-service:8083/savingService-Tien/
logging.level.org.springframework.security=DEBUG
