spring:
  application:
    name: NotificationService

  datasource:
    url: jdbc:postgresql://26.41.201.183:5432/postgres
    username: postgres
    password: 2162004
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084
  servlet:
    context-path: /noti-Nguyet

jwt:
  secret: "/dDMtv80KZSwPmYUT6r0Qj6LJNpSwCmwt7hqv0x5hc+RgNz3v6bFYVF3IrWjTsxLj//ddVXi34mNrEZ454nmGg=="
  expiration: 86400000
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  endpoint:
    prometheus:
      enabled: true